### ISSUE TITLE
CSV Deploy Problem

### ISSUE THREAD

**Issue by AliYLDRM** [amintalkin/MyBot-AIO#28]
I'm using CSV attacks. All soldiers, archers, etc. Barbara king queen does not deploy.

Sorry bad english.

**Comment by hokiepokedad** [comment]
This issue exists because of the use of Fast ADB Clicks and/or high CSV Deploy speeds.  Either of those settings may, most likely, produce "missed" clicks and therefore some troops may not deploy.

Question though:  Are you saying the heroes do not drop also?

See #26 .

**Comment by AliYLDRM** [comment]
"enable fast adb click" checkbox not selected. I'm using BlueStacks.
It does not recognize that the Trop be deployed. I take for you to explore if you have a file you want.

**Comment by davidwassaved** [comment]
HI there! FF Spiral by Awesomegamer is not deploying or using all the troops. About 30-40 Barch remain in my army camp. It does not get all the loots because the troops were not enough. I am a huge fan of this MOD since the earlier versions so please if you have time to take look at this. I am using MEmu and "Enable fast adb click" was unchecked. I am also using lowest speed deployment.

**Comment by hokiepokedad** [comment]
I have just checked in additional fixes that further fixes timings and drops.  In addition, my new feature to drop remaining troops will be included in 2.0.9.

**Comment by davidwassaved** [comment]
Thanks man! Can't wait for the next release.
